### ISSUE TITLE
iago-1.soln is not a valid plan

### ISSUE THREAD

**Issue by guicho271828** [patrikhaslum/INVAL#2]
The plan should fail at step 3: When `(take Emilia handkerchief bedroom)`, Desdemona is still in the room and Emilia cannot steal the handkerchief. 

* In the initial state, `(at Desdemona bedroom)` is true.
* Action 1 `(request-has Iago Iago handkerchief)` does not move Desdemona.
* Action 2 `(goto Emilia bedroom garden)` neither.
* Action 3 `(take Emilia handkerchief bedroom)` requires `(alone-at ?a ?p)=(alone-at emilia bedroom)` which does not hold:

```lisp
; Proving axiom (ALONE-AT EMILIA BEDROOM)
; binding ?C ?P -> EMILIA BEDROOM
;; (CHARACTER EMILIA) -> ⊤
;; (PLACE BEDROOM) -> ⊤
;; binding ?D -> IAGO
;; (CHARACTER IAGO) -> ⊤
;; (AT IAGO BEDROOM) -> ⊥
;; binding ?D -> OTHELLO
;; (CHARACTER OTHELLO) -> ⊤
;; (AT OTHELLO BEDROOM) -> ⊥
;; binding ?D -> EMILIA
;; (CHARACTER EMILIA) -> ⊤
;; (AT EMILIA BEDROOM) -> ⊤
;; (LOCATABLE EMILIA) -> ⊤
;; (PLACE BEDROOM) -> ⊤
;; (= EMILIA EMILIA) -> ⊤
;; binding ?D -> DESDEMONA
;; (CHARACTER DESDEMONA) -> ⊤
;; (AT DESDEMONA BEDROOM) -> ⊤
;; (LOCATABLE DESDEMONA) -> ⊤
;; (PLACE BEDROOM) -> ⊤
;; (= DESDEMONA EMILIA) -> ⊥
; (ALONE-AT EMILIA BEDROOM) -> ⊥
```

I tested it with [my own validator](https://github.com/guicho271828/ArriVAL).

**Comment by patrikhaslum** [comment]
Yes, the plan is invalid, and INVAL correctly identifies where the plan fails.
I've added a comment to the plan file to avoid confusion.

**Comment by guicho271828** [comment]
I see, it was intended.

**Comment by patrikhaslum** [comment]
It was probably more of an accident than intentional. But it's not a bug.
